name = "hellgates"
main = "build/worker/shim.mjs"
compatibility_date = "2025-09-01"
minify = true
workers_dev = false

routes = [
  # Main Domain
  { pattern = "alviola.biz.id", custom_domain = true },

  # Wildcards
  { pattern = "blog.skillacademy.com.hell.alviola.biz.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "HELL"
id = "8792503062e048c3b399a8459563a24f"

[build]
command = "cargo install -q worker-build --version 0.1.4 --force && WASMOPT=0 worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build --version 0.1.4 --force && WASMOPT=0 worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/eikarna/SirenWeb/refs/heads/main/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/eikarna/SirenWeb/refs/heads/main/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/eikarna/SirenWeb/refs/heads/main/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/eikarna/SirenWeb/refs/heads/main/converter.html"

[observability.logs]
enabled = true

[placement]
mode = "smart"
